### ISSUE TITLE
Cannot close the "add new functions" window [bug]

### ISSUE THREAD

**Issue by 4332weizi** [noah-nuebling/mac-mouse-fix#72] opened 2021-03-25 08:26 UTC
## Description

I cannot close the "add new functions" window after opening it.

## Steps to reproduce

1. Open "Mac Mouse Fix" app
2. Click the " " icon
3. Do something or noting
4. Click the "Cancel" button

## Context

Mac Mouse Fix Version: 2.0.0 Beta 1
macOS Version: Big Sur 11.2.3
Mouse Model: HP S300

## Additional Comments

MacBook Pro with Apple Silicon

---

### Console Logs

https://pastebin.com/aRGEHY0C

### Crash Reports

–

**Comment by noah-nuebling** [comment] 2021-03-25 14:21
Hi @4332weizi, thanks for your feedback, and for taking the time to attach some console logs!

Despite your great feedback, I'm not sure why this is happening yet, unfortunately.

Here are some more things you could check to help figure this out:

- Check if this still happens when you have Mac Mouse Fix disabled
- Check if this still happens when you uninstall all old versions of Mac Mouse Fix and then restart your machine
- Check if the window closes when you click a button over the '+' field
- Tell me where Mac Mouse Fix located on your system
- Tell me if there's anything else not working in Mac mouse fix or other software that might be related
- Tell me if you are running any other software installed that you think could  be interfering with mouse input

If you have time to test/answer any of these, or find out anything else, just let me know and I'll be sure to look into it.

**Comment by 4332weizi** [comment] 2021-03-26 06:10
Hey Noah, thanks for the response.

 > Check if this still happens when you have Mac Mouse Fix disabled

Add or remove new functions is disabled when Mac Mouse Fix is disabled.

> Check if this still happens when you uninstall all old versions of Mac Mouse Fix and then restart your machine

I reinstalled it, and it still does not work for me.

> Check if the window closes when you click a button over the '+' field

The window still opens when clicking over the '+' field.

> Tell me where Mac Mouse Fix located on your system

`Mac Mouse Fix. app` is located in the `/Applications` folder.

> Tell me if there's anything else not working in Mac mouse fix or other software that might be related

Not found currently.

> Tell me if you are running any other software installed that you think could be interfering with mouse input

No, I got this mac only four days. I think there is no other software interfering with mouse input installed.

Here is the screen record:

https://user-images.githubusercontent.com/5563945/112589268-c7216000-8e3b-11eb-8eef-f0b8da37a427.mov

**Comment by noah-nuebling** [comment] 2021-03-26 09:59
> Add or remove new functions is disabled when Mac Mouse Fix is disabled.

Oh true. You should also be able to __disable__ Mac Mouse Fix from the Terminal by running this command:

```shell
/bin/launchctl bootout gui/${UID} ~/Library/LaunchAgents/com.nuebling.mac-mouse-fix.helper.plist
```

And re-__enable__ it by running:

```shell
/bin/launchctl bootstrap gui/${UID} ~/Library/LaunchAgents/com.nuebling.mac-mouse-fix.helper.plist
```

So to test if this still occurs when Mac Mouse Fix is disabled, you could:

1. Open Mac Mouse Mouse Fix and make sure it is enabled so the '+' button is clickable.
2. Run the terminal command for disabling Mac Mouse Fix. The user interface will not react to this and the '+' button will still be clickable.
3. Now can open the '+' window while Mac Mouse Fix is disabled and test if that helps with your issue.

You could also try to reset the Mac Mouse Fix configuration file to default. Maybe it became corrupted or something. To do that:
1. Disable Mac Mouse Fix and close it.
2. Delete the config file by running this Terminal command:
    ```
    rm ~/Library/Application\ Support/com.nuebling.mac-mouse-fix/config.plist
    ```
3. Re-open Mac Mouse Fix.

Maybe you could also save the old config file before deleting it so I can take a look at it if it turns out to be the cause of the problem.

Thanks for your thorough answer!

**Comment by 4332weizi** [comment] 2021-03-26 11:24
It seems still not working, I will retry it next week.

**Comment by 4332weizi** [comment] 2021-03-29 06:24
I tested it on another new MacBook Pro and it didn’t work either.

I also debugged it with XCode,  function `end` called as expected, but the window was not closed.

```
+ (void)end {
    [AppDelegate.mainWindow endSheet:_instance.window];
}
```

![image](https://user-images.githubusercontent.com/5563945/112794939-5d52c180-909a-11eb-8c1f-3498a7951a6e.png)

**Comment by noah-nuebling** [comment] 2021-03-29 07:11
Oh that's great that you debugged it!

I added some extra function calls for closing the AddWindow in the build below. I'm not sure at all that that's going to help,  but I think it's worth a try if you want to check it out.

[Mac Mouse Fix.app.zip](https://github.com/noah-nuebling/mac-mouse-fix/files/6219901/Mac.Mouse.Fix.app.zip)

Btw Is the new machine you tested running on an M1 chip as well?

**Comment by 4332weizi** [comment] 2021-03-29 07:32
Yes I tested with a new MacBook with M1 chip, and I asked my friend test it on MacBook Pro (13-inch, 2018) just now, both not working. Notice that these three Mac runing `macOS Big Sur 11.2.3`.

This new version still not working.

**Comment by 4332weizi** [comment] 2021-03-29 09:03
Finally find that `initialize` was called twice, _instance cannot point to the right `AddWindowController` instance.

**Comment by noah-nuebling** [comment] 2021-03-29 13:09
Awesome, good job, thanks for you work!

**Comment by noah-nuebling** [comment] 2021-03-29 13:10
But it's still really weird to me that I never saw it, I'm also running `macOS Big Sur 11.2.3`

**Comment by 4332weizi** [comment] 2021-03-29 14:39
I upgrade my old MacBook Pro (13-inch, Early 2015) to `macOS Big Sur 11.2.3`, can not reproduce this problem.

![image](https://user-images.githubusercontent.com/5563945/112852784-d411ae00-90de-11eb-8c83-ca52acc6a1dd.png)

**Comment by noah-nuebling** [comment] 2021-03-29 14:50
I actually have the same model. Interesting.

**Comment by noah-nuebling** [comment] 2021-03-29 16:17
I just released a [new Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases) including your pull request. Thanks again for contributing! :)

**Closed as completed by noah-nuebling** 2021-03-29 16:17 UTC
