### ISSUE TITLE
Smooth scrolling doesn't scroll terminal/iterm [bug]

### ISSUE THREAD

**Issue by trivita** [noah-nuebling/Mac-Mouse-Fix#429] opened 2022-10-31 03:12 UTC
## Description

if smooth scrolling is enabled, mouse scroll won't work in system terminal or iterm2.

## Steps to reproduce

1. enable smooth scrolling
2. scroll in terminal or iterm2 wont work

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: macos monterey 12.6
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment] 2022-10-31 11:26
Hi @trivita, thanks for reaching out!

This is a known issue with Mac Mouse Fix 3.0.0 Beta 4.

But I can't reproduce it under 2.2.3. Are you surely using 2.2.3?

If you are using 3.0.0 Beta 4, then I recommend you downgrade to [Beta 3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-3) for the time being.

Let me know if you have any more questions!

**Comment by noah-nuebling** [comment] 2022-11-03 14:55
This problem should be fixed in [3.0.0 Beta 5](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-5)!

If 3.0.0 Beta 5 still doesn't work for you, please open a new issue or let me know so I can reopen this issue. Thanks!

Also see #413. I've made that the 'main issue' for the problem that 3.0.0 Beta 5 attempts to fix.

**Closed as completed by noah-nuebling** 2022-11-03 14:55 UTC
