### ISSUE TITLE
bug: when I login to other account gestures does not work [other]

### ISSUE THREAD

**Issue by suredanish** [noah-nuebling/Mac-Mouse-Fix#686] opened 2023-10-17 15:33 UTC
when I login to other account gestures does not work, even scrolling does not work.
I disable and enable Mac Mouse Fix. Then every thing works fine.

**Comment by thenktor** [comment] 2023-10-20 06:18
Duplicate of #600

**Comment by noah-nuebling** [comment] 2024-01-15 06:55
Hey there, I just fixed the issue in the latest release [3.0.1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.1)!

Let me know if you have any more questions.

**Closed as completed by noah-nuebling** 2024-01-15 06:55 UTC
Labels: Fast User Switching
