### ISSUE TITLE
Option to assign side buttons as ⌘ [ and ⌘ ] [enhancement]

### ISSUE THREAD

**Issue by w5nh6o** [noah-nuebling/mac-mouse-fix#156] opened 2021-09-09 13:57 UTC
## Description
Please allow an extra option to assign side buttons as ⌘ [ and ⌘ ] hotkeys.

## Rationale
The current options work... To an extent. Back and forward buttons work in browsers, but do not get recognised in other applications such as Finder, Notion, etc.
The hotkeys ⌘ [ and ⌘ ] are used quite universally in macOS apps. Having this as an option will increase the usefulness of side buttons for end users.

## Additional info
Some people may not like the back and forward implementation as ⌘ [ and ⌘ ] hotkeys due to the fact that the hotkey will highlight a section at the top menu bar (creating a blink effect that they can spot at the corner of their eyes). Hence, it's better to provide this feature as extra option instead of a replacement.

**Comment by noah-nuebling** [comment] 2021-10-11 02:28
Hey @W5nH6o thanks so much for the feedback!

I agree that the problem of different apps having different methods for going back is very much worth addressing.

In version 2 you can actually assign the side buttons to ⌘ [ and ⌘ ]. You can download version 2 [here](https://github.com/noah-nuebling/mac-mouse-fix/releases). The problem is that this won't work for all apps, either, and it also makes the menu bar flash.

Ideally MMF could automatically choose the appropriate way of telling the current app to go back, or there could be app specific settings.

I'd love to implement those features, but it is a long way off at this point.

If you have any more questions, let me know!

**Comment by noah-nuebling** [comment] 2022-01-05 17:55
Also see #162

**Comment by noah-nuebling** [comment] 2022-09-06 20:56
Hey! I'll close this since #85 is now the dedicated place for discussion around this feature.

**Closed as completed by noah-nuebling** 2022-09-06 20:56 UTC
Labels: Universal Back and Forward
