### ISSUE TITLE
"Invert" option for "Scroll & navigate" [enhancement]

### ISSUE THREAD

**Issue by tkafka** [noah-nuebling/Mac-Mouse-Fix#705] opened 2023-11-05 14:31 UTC
## Description
Hello, I would like an option to have the "Scroll & navigate" click and drag action invert the movement - so that when I click and drag up, the page actually scrolls up (like if I dragged it with my finger on the iPhone).

## Rationale
This feels natural to me, as it would work just on the touchscreen devices.

## Additional info
–

**Comment by timmb** [comment] 2023-11-10 16:29
Possible duplicate of https://github.com/noah-nuebling/mac-mouse-fix/issues/661

**Comment by noah-nuebling** [comment] 2023-12-15 23:32
Hey there! The drag direction should be fixed in [3.0.0 Beta 7](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-7). If you have other probems you want addressed please open new issue for that. Thank you.

**Closed as completed by noah-nuebling** 2023-12-15 23:32 UTC
Labels: 3.0.0 Beta 6 Click and Drag Direction

**Comment by tkafka** [comment] 2023-12-20 14:27
This is awesome, works just like I wanted, thank you! You best nailed the feeling of having the actual magic mouse (minus the awful ergonomics). Purchased the licence right away :).

**Comment by noah-nuebling** [comment] 2023-12-25 04:07
Nice, I'm glad you're enjoying it, thanks for sharing! :)
