### ISSUE TITLE
Works great, but after a few hours it disables itself and reenables after a few minutes

### ISSUE THREAD

**Issue by Retch** [noah-nuebling/mac-mouse-fix#30] opened 2020-03-18 09:59 UTC

**Comment by tomsotte** [comment] 2020-04-18 14:10
It happens to me as well on macOS Catalina 10.15.4

**Comment by noah-nuebling** [comment] 2021-03-03 02:03
Hey there, thank you guys for reaching out, and sorry for tending to this so late. 

This is really weird, I'm not sure what might be causing that. 
It sounds a little bit like it could be crashing in the background over and over again, causing the system to disable it for a few minutes. That's the only thing I can think of at the moment. If you guys could open a [bug report](https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=bug-report) and see if you can find any related crash logs on your system that would be super helpful!

Are you guys using an older macOS version by any chance?

**Comment by Retch** [comment] 2021-03-05 21:25
I will make a bug report, but i haven't seen this bug recently. I was using Catalina as i noticed the bug.

**Comment by tomsotte** [comment] 2021-03-05 22:09
I'll try to file a bug report as well but lately it has not happened anymore. On the other hand sometimes it's even reproducible, like I know I can open and scroll on a certain app that made it crash once, and it will make it crash again. (Crash as in auto disabling and having to re-enable it)

**Comment by tomsotte** [comment] 2021-03-18 09:17
Without opening another issue for the bug report, I'll write here. It happened to me and I've got a crash log for it but couldn't see system logs because I've opened the console too late it seems.

## Context

Mac Mouse Fix Version: 1.0.1
macOS Version: 10.15.7
Mouse Model: NewWay ON-MO-A3E

### Console Logs

–

### Crash Reports

https://pastebin.com/BUywfxVU

**Comment by tomsotte** [comment] 2021-03-18 09:24
It just happened again. It might be correlated to scrolling in the Android emulator. If I have the time to properly try to reproduce it I'll let you know.

**Comment by noah-nuebling** [comment] 2022-09-06 19:00
Hey guys, closing this for now, let me know if it's still an issue!

**Closed as completed by noah-nuebling** 2022-09-06 19:00 UTC
