### ISSUE TITLE
Default Shift key like a modification for scroll for horizontal don't work in Figma [bug]

### ISSUE THREAD

**Issue by unS0uL** [noah-nuebling/Mac-Mouse-Fix#657] opened 2023-09-06 17:13 UTC
## Description

Soft build: (21668)
Figma(web) has default keys shortcuts for scrolling. One these shortcuts is toggle (shift + scroll up\down) for horizontal scrolling.
If enable Mac mouse fix, that shortcut doesn't work in Figma. I cleared all shortcuts in Mac mouse fix and shortcut in Figma didn't work. Maybe another app\web app, which has shift like a modification for scroll didnt working, i don't testing it with another app. 

## Steps to reproduce

1. Enable app feature
2. Open figma.com
3. Open project
3. Press down SHIFT key and use scroll up\down, for scrolling horizontally

## Context

Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: Monterey
Mouse Model: Logitech G700

**Comment by noah-nuebling** [comment] 2024-01-17 07:05
Hi there, @unS0uL, I can't reproduce this I think. 

Shift for horizontal scrolling works fine for me in Figma. If I remove the keyboard modifier for horizontal scrolling in MMF, then it won't work anymore, but I think this is desirable behaviour.

I'm closing this now, assuming it has been fixed. If you still experience these problems, please open a new issue. Thank you.

**Closed as completed** 2024-01-17 07:05 UTC
