### ISSUE TITLE
Activation period started at day 7 / 90 [bug]

### ISSUE THREAD

**Issue by ericsodt** [noah-nuebling/Mac-Mouse-Fix#728] opened 2023-12-15 23:52 UTC
## Description

When I downloaded the 3.0 beta, it looks as though I have a 90 day trial.  The problem I am seeing is that it starts you off on day 7, rather than day 1

## Steps to reproduce

Go to about and view 

## Context

Mac Mouse Fix Version: 3.0.0 Beta 7
macOS Version: 12.7.1
Mouse Model: Logitech M325

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment] 2023-12-16 01:02
Hey there @ericsodt, thanks for reaching out! Are you sure you've never used Mac Mouse Fix 3 before? I can't reproduce this issue, and I haven't heard about the issue before. But if more people report it I'll look into it.

I hope that makes sense and is okay. If you have more questions or concerns, let me know.

**Comment by noah-nuebling** [comment] 2024-01-22 04:19
I'll close this now, assuming it's been resolved.

Also, if you experienced this issue, just shoot me an email and I can provide you with a free license/refund. (For a refund send along the email adress with which you bough the app.)

I hope that works! If there are still issues with the trial counter, let me know.

**Closed as completed by noah-nuebling** 2024-01-22 04:19 UTC
Labels: UI/Trial/License Bugs
