### ISSUE TITLE
Mouse scrolling with wheel doesn't work on iTerm2 if Smooth Scrolling is enabled (Beta 4) [bug]

### ISSUE THREAD

**Issue by jaekyeom** [noah-nuebling/Mac-Mouse-Fix#413] opened 2022-10-20 10:27 UTC
## Description

I think MMF 3.0.0 Beta 3 didn't have this issue, but Beta 4 has.

## Steps to reproduce

1. Enable Mac Mouse Fix 3.0.0 Beta 4 (19384)
2. Enable Smooth Scrolling
3. Try scrolling with the wheel on iTerm2

## Context

Mac Mouse Fix Version: 3.0.0 Beta 4
macOS Version: 12.0.1 (21A559)
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by nickcolea** [comment] 2022-10-20 14:04
The problem seems to be wider than just iTerm. 
The standard terminal doesn't work either, nor does any application that employs a drop-down box or similar scroll-dependent elements.

**Comment by noah-nuebling** [comment] 2022-10-20 14:05
Hey guys just wanna let you know I think I know why this is happening and I'm working on it!

**Comment by leehuwuj** [comment] 2022-10-24 07:26
i get the same issue with Iterm2. Is there any temporary solution for this?

**Comment by noah-nuebling** [comment] 2022-10-24 10:02
Can you downgrade to beta 3?

**Comment by noah-nuebling** [comment] 2022-11-03 15:13
Hey guys, this problem should be fixed in [3.0.0 Beta 5](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-5)!

If you still experience this problem under 3.0.0 Beta 5, please open a new issue or let me know so I can reopen this one. Thank you!

**Closed as completed by noah-nuebling** 2022-11-03 15:13 UTC

**Comment by laznp** [comment] 2022-11-03 18:30
I've just got this scrolling issue on 3.0.0 Beta 4 on MacOS Ventura, can't scroll on iTerm and Launchpad.
Then I try update to 3.0.0 Beta 5. The issue was solved! Thank you very much! @noah-nuebling

**Comment by noah-nuebling** [comment] 2022-11-03 18:31
Great, thanks for getting back @laznp!

**Comment by spencercharris** [comment] 2022-11-03 19:35
Issue confirmed resolved for #427 - Thank you!

**Comment by ocontant** [comment] 2024-08-05 07:46
I have this issue currently on 3.5.3 

Am I the only one?

**Comment by featalion** [comment] 2024-09-16 12:37
Just got the same issue on 3.5.4, macos 14.6.1. The scrollbar moves, but the content does not change. If I restart the app it does not help, but if I restart my laptop it fixes the problem temporary.

**Comment by noah-nuebling** [comment] 2024-09-20 21:29
Hey guys, I'm on iTerm 3.5.4, macOS 15.0, Mac Mouse Fix 3.0.3, and scrolling is working well on my end.

I'm not if this might be an iTerm issue. Does it make a difference if you change the scrolling smoothness in MMF or if you disable MMF?
