### ISSUE TITLE
Side buttons not working in 2.0/2.1, but used to work in 1.0.4 [bug]

### ISSUE THREAD

**Issue by roussanoff** [noah-nuebling/Mac-Mouse-Fix#211] opened 2022-01-14 14:17 UTC
## Description

I have Logitech MX Vertical Ergonomic Wireless Mouse. I am on Mojave 10.14.6. The app used to work perfectly when I was on MMF 1.0.4. I tried upgrading to MMF 2.0 and then 2.1 but the app simply does not register the side buttons anymore. They are performing Back and Forward operations in every app no matter what I set in MMF. Moreover, when I try to set "customized button" using a plus icon, the events from the side buttons are not registered (hitting the usual Left Button results in the expected "Primary Mouse Button can't be used" message).

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.1.0
macOS Version: 10.14.6
Mouse Model: Logitech MX Vertical Ergonomic Wireless Mouse

## Additional Comments

Could you perhaps consider releasing a re-signed version of 1.0.4? It does not work anymore because the signature expired. 

---

### Console Logs

NA

### Crash Reports

NA

**Comment by roussanoff** [comment] 2022-01-14 19:05
Small update: tried to do a clean install of 2.1 using [AppCleaner](https://freemacsoft.net/appcleaner/), that did not resolve the issue. Smooth scrolling and direction inversion work correctly.

**Comment by noah-nuebling** [comment] 2022-01-14 19:26
Hey there Vasily, thanks for your feedback!


This is weird because your mouse buttons shouldn't perform back and forward actions by themselves. You normally need to have a mouse driver do that for you.

There are 4 explanations for this that I can think of:

1. Some other mouse driver is running in the background.
    - Maybe you've used some other mouse driver like Logitech Options, that still has its daemon running in the background, which intercepts your mouse clicks before Mac Mouse Fix can?
    - I don't think so, but it might be an old version of MMF. MMF should take care of this by itself but to double check you could open Activity Monitor and  search for "Mouse Fix Helper". If "Mouse Fix Helper" still shows up after you uncheck the "Enable Mac Mouse Fix" checkbox in the app then there's possibly a conflict with some old version.

2. Some other mouse driver has reconfigured your mouse. I know that SteerMouse, and Logitech Options can make permanent changes to your mouse that persist even after you uninstall those apps. USB Overdrive and other drivers might be able to do this too. I'm not sure. Mac Mouse Fix can't do this. It has absolutely no effect on your mouse if "Mouse Fix Helper" is not running. 
    - So what could've happened is that some other driver has reconfigured your mouse to send back and forward events instead of normal click events. Mac Mouse Fix can only read normal click events. 
    - If you think some other driver might have reconfigured your mouse, then you could try to reinstall one of those drivers and use it to reconfigure your mouse to send normal click events. 

3. Your Mac Mouse Fix configuration has gone bad. You can restore the default configuration like this:
    - https://user-images.githubusercontent.com/40808343/149573730-f5a8b6bb-adde-49c2-81ca-acab967cca25.mp4
    - 3.1 Maybe the file permissions on the Mac Mouse Fix configuration file or any enclosing folder have been corrupted. 
        - This might make it impossible for MMF to change the configuration of the sidebuttons from "Back and Forward" to something else. Use Command-I with a file selected to check and update its permissions.

4. There is something about the security mechanisms in macOS that broke, and prevents Mac Mouse Fix from receiving click events from your mouse.
    - I don't think this is the case, since smooth scrolling still works for you, and intercepting scroll events works throught the same security mechanism as intercepting click events. But if you want to be absolutely sure, you could
        1. Uninstall all versions of Mac Mouse Fix
        2. Delete Mac "Mouse Fix Helper" from your accessibility settings:
            - https://user-images.githubusercontent.com/40808343/149572887-d02a43e8-ebf5-45f3-969d-19ad25623c43.mp4
        3. Reinstall the latest version
        4. Give "Mac Mouse Fix Helper" accessibilty access, like this: 
            - https://user-images.githubusercontent.com/40808343/149573112-06ac3559-62e4-4326-a444-3d3dbbd48947.mp4

 I also rebuilt and signed 1.0.4 for you to test:

[MacMouseFix-1.0.4-New-Signature.app.zip](https://github.com/noah-nuebling/mac-mouse-fix/files/7872725/Mac.Mouse.Fix.app.zip)

Hope that helps! Let me know if you have any more questions or if I can clarify anything for you.

Update: Since you used AppCleaner, that should already have reset your configuration to default. So you probably don't need to check for "3."

**Comment by rtrembecky** [comment] 2022-01-15 18:56
hey, wow, actually, I had the same problem and it solved by the suggestion number 4! thanks. @roussanoff maybe it will be your case, too.

however, there was this problem where you start the newly "installed" app and it is already enabled, but doesn't have the accessibility rights... in this case it lags everything for 5 seconds whenever you use e.g. middle button or so 😅  the key is to disable Mac Mouse Fix and after re-enabling it is asks for the accessibility rights.

@noah-nuebling maybe you could add this accessibility rights check on each app's startup and disable it if rights are missing? I've noticed this behavior before and it could confuse users.

**Comment by noah-nuebling** [comment] 2022-01-15 20:21
@rtrembecky Oh cool that's great to hear! 

> however, there was this problem where you start the newly "installed" app and it is already enabled, but doesn't have the accessibility rights... in this case it lags everything for 5 seconds whenever you use e.g. middle button or so

I can't reproduce this, If you can, it would be awesome if you could post a step by step. Thanks!

**Comment by roussanoff** [comment] 2022-01-16 02:48
I went through all the steps without success, and also tried a much more common Logitech Marathon m705 mouse to be sure it's not mouse-specific.

1. I had Logitech Control Center and USB Overdrive installed previously. I noticed that USB Overdrive Helper is still in the Login Items. I removed it, then installed USB Overdrive, and then uninstalled it using their suggested uninstaller. After I did that, I stopped observing the behavior of Back and Forward functionality (these buttons simply do not work anymore, just as @noah-nuebling said). I also searched my Extensions using the procedure outlined [here](https://www.usboverdrive.com/index.php/support/)  and did not find any Logitech or other options.
2. I could not check that it's the case. When I launch Mac Mouse Fix, I see a message "captured buttons 4 and 5". Does this indicate that the problem is not the different event? I also have Karabiner Elements installed, but that should only affect the keyboard, and I made sure that mouse options are not enabled. 
3. Yes, did that both manually and using AppCleaner.
4. Yes, although the app disappears from Accessibility Access options if I uninstall it. I have to first revoke the permission to use Accessibility features and _then_ remove the app. Otherwise, the app disappears from the list and then MacOS remembers that permission had previously been granted. When I reinstall the app, it has the permission. I did remove the permissions and go through "please enable Accessibility access" prompt.

Thank you for rebuilding 1.0.4, it works without issues no matter how I install it. I will keep using that version until I retire this machine, which will happen very soon.

**Comment by noah-nuebling** [comment] 2022-01-16 04:13
Hey @roussanoff, Thanks for doing all this testing and getting back about it!
I'm glad that 1.0.4 works for you. Let me know if you still have trouble using version 2 on your new machine.

**Comment by noah-nuebling** [comment] 2022-10-27 16:41
Hey guys, I'm finally having a serious look at the issues under Mojave. But I'm having trouble trying to debug the app on older versions of macOS.

#### If any of you guys have any experience or tips on how to debug on older macOS versions I would love your input!!

I also posted a question on StackOverflow:
https://stackoverflow.com/questions/74224459/how-to-debug-mac-app-on-older-macos-version

**Comment by noah-nuebling** [comment] 2022-10-30 17:44
Hey @roussanoff, I just released Mac Mouse Fix [2.2.3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.2.3) specifically to make the experience better on older macOS versions!

Unfortunately couldn't reproduce your issue so far, so it's probably not fixed, yet. [This comment](https://github.com/noah-nuebling/mac-mouse-fix/issues/246#issuecomment-1296310576) contains info on how you can help figure this problem out if you're interested.

I'll close this Issue now so all the discussion around this problem is focused in #246. 

If you think your issue is different from the one described in #246, please open a new issue or let me know so I can reopen this one. Thank you!

**Closed as completed** 2022-10-30 17:59 UTC
Labels: macOS 10.14 Incompatibility
