### ISSUE TITLE
Does not work with multiple Users

### ISSUE THREAD

**Issue by daletman** [noah-nuebling/Mac-Mouse-Fix#622] opened 2023-07-19 15:29 UTC
## Description

Scrolling doesn't work when two users are logged in and both use the app

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: 12.6.7 (21G651)
Mouse Model: Logitech MX Master 2S

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by Pogimon3** [comment] 2023-07-21 18:46
Same issue here. Temporary fix while this gets addressed in the code: You can disable mac mouse fix and re-enable it every time you switch user account to make it work.

**Comment by daletman** [comment] 2023-07-21 19:51
> Same issue here. Temporary fix while this gets addressed in the code: You can disable mac mouse fix and re-enable it every time you switch user account to make it work.

Didn't work when I tried it

**Comment by thenktor** [comment] 2023-07-26 08:57
duplicate of #600

**Comment by noah-nuebling** [comment] 2024-01-15 06:56
Hey there, I just fixed the issue in the latest release [3.0.1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.1)!

Let me know if you have any more questions.

**Closed as completed by noah-nuebling** 2024-01-15 06:56 UTC
Labels: Fast User Switching
