### ISSUE TITLE
Scroll randomly behaves like zoom

### ISSUE THREAD

**Issue by KirksFletcher** [noah-nuebling/mac-mouse-fix#36] opened 2020-07-27 08:04 UTC
BUG: When using the side buttons to flick back and forth between spaces, every now and then the scroll will suddenly behave like i have ctrl held down and zoom in and out of the page instead of scrolling up and down. if i leave it for a second it will start scolling up and down as expected (without me changing anything). Obviously annoying as I have to reset my page zoom level using ctrl + 0. Any ideas on this?

**Comment by noah-nuebling** [comment] 2020-08-31 18:30
Hey Kirk, thanks for your feedback!

Unfortunately I can't reproduce your issue. I'm on 0.9.2. Beta 5 at the moment which you can download [here](https://github.com/noah-nuebling/mac-mouse-fix/releases/download/0.9.2-Beta-5/Mac-Mouse-Fix-0.9.2-Beta-5.zip). 

Using this newer version might fix your issue, if not it would be awesome if you let me know, so I can look into your problem further.

**Comment by noah-nuebling** [comment] 2021-05-07 17:10
I'm closing this Issue now. I assume I'll hear about it if it's a more widespread problem.

@KirksFletcher if you have any ideas or leads as to what might be causing this let me know!

**Closed as completed by noah-nuebling** 2021-05-07 17:10 UTC
