### ISSUE TITLE
Cannot load on Catalina

### ISSUE THREAD

**Issue by felixakiragreen** [noah-nuebling/mac-mouse-fix#16] opened 2019-10-09 00:38 UTC
Just updated to Catalina (10.15.0)
![Screen Shot 2019-10-08 at 20 37 52](https://user-images.githubusercontent.com/1843672/66443042-86e1de00-ea0b-11e9-8c2a-0fd7a1031130.png)

(Please note: this is after I went to "Security & Privacy" and clicked "Open Anyway")

**Comment by hacker1024** [comment] 2019-10-09 08:09
I have this issue as well.

**Comment by noah-nuebling** [comment] 2019-10-11 14:35
Hi there thank you for your feedback! I don't know what might be the cause of this error. Are there any crash logs related to Mac Mouse Fix in ~/Library/Logs/DiagnosticReports/ ? Anything with "legacyloader" or "mouse fix" in its name might be relevant.

**Comment by noah-nuebling** [comment] 2019-10-12 17:47
Opening Console.app and filtering by 'mouse fix' or 'legacyLoader' might also shine some light on the issue.

**Comment by hacker1024** [comment] 2019-10-20 04:05
The latest Catalina supplemental update (19A602) has fixed all my third party preference panes.

**Comment by noah-nuebling** [comment] 2019-10-20 08:07
That’s great, thank you for informing me! Does anyone still have this issue?

**Comment by toastmonger** [comment] 2019-10-20 18:56
Thanks for the work you do on this, truly appreciated.

I still have this issue.  Updated to catalina macOS 10.15 (19A602), but I cannot install mousefix. Getting “Mouse Fix.prefPane” can’t be opened because Apple cannot check it for malicious software.  If I ignore the message then I get "Preferences Error","Could not load Mouse Fix preference pane." (the original error for this issue)

I noticed you closed [https://github.com/noah-nuebling/mac-mouse-fix/issues/17](url) without additional comment.  Seems related.

**Comment by noah-nuebling** [comment] 2019-10-23 13:24
Hey Toastmonger, thanks! :)

Unfortunately, the semester started this week, so I don't have a lot of time to work on Mac Mouse Fix at the moment, but if you send me your crash logs, I will try to look into it soon.

I described how to obtain the crashlogs in a previous comment.

---

Regarding the other issue I closed: Unfortunately, I won't be able to notarize the app without buying a 99$ Apple Developer account. This is also the reason why the "can’t be opened because Apple cannot check it for malicious software" message appears. However, the app should still work properly once you click 'Open Anyway'. I think the reason why the app won't work on your computer is probably either a bug in the new System Preferences app or with Gatekeeper.

So I think there is a good chance that your issue will be fixed with a future macOS update, or maybe I can find a workaround if someone with this issue sends me the crashlogs.

**Comment by toastmonger** [comment] 2019-10-24 02:33
Noah, thanks for your response.  I tied myself over by grabbing the source, signing it for personal use/development, and building it.  I will try to reinstall when I get the chance with a copy from your website.

I had another mac on mojave which took the install without a hitch, since I have updated that one to catalina and there were no warnings or complaints when used (the already installed) mac-mouse-fix.

**Comment by noah-nuebling** [comment] 2019-10-25 11:33
Hey Toastmonger,

So it works when you compile / sign it yourself but not when you download it from the website? That might be a very important clue.

**Comment by toastmonger** [comment] 2019-10-26 06:35
That's correct, couldn't install it when I downloaded the app from your website, but was able to install when i signed myself and built from source.

**Comment by noah-nuebling** [comment] 2019-10-28 19:20
Okay, that's interesting! Thank you for your help! 👍 

I think this means that the two most likely explanations are:

a) It's an issue with Gatekeeper/signing/notarization. Possibly a bug on Apples' side.
b) I accidentally fixed the error between the latest release and the source code you downloaded.

**Comment by l4zaro** [comment] 2019-11-07 15:01
Hello, I'm also getting an error:
“Mouse Fix.prefPane” can’t be opened because Apple cannot check it for malicious software.

With:
Mac OS Catalina "10.15.1 (19B88)"

Trying to open-anyways with security-privacy did not work.

**Comment by jinialadin1** [comment] 2019-11-20 05:04
I had a same issue and this code helped me.
`sudo xattr -r -d com.apple.quarantine [Path of your prefpane]`

Hope this would help the same issue.

**Comment by luisadnsaavedra** [comment] 2019-12-06 11:56
> I had a same issue and this code helped me.
> `sudo xattr -r -d com.apple.quarantine [Path of your prefpane]`
> 
> Hope this would help the same issue.

This fixed it for me, thank you!

**Comment by daeh** [comment] 2020-01-30 19:44
> I had a same issue and this code helped me.
> `sudo xattr -r -d com.apple.quarantine [Path of your prefpane]`
> 
> Hope this would help the same issue.

I had the signing issue on the latest version of Catalina (10.15.3) and this fixed it. Might help others to have the fix on the landing page.

**Comment by hinzpak** [comment] 2020-02-12 19:48
> I had a same issue and this code helped me.
> `sudo xattr -r -d com.apple.quarantine [Path of your prefpane]`
> 
> Hope this would help the same issue.

this works great!!! thanks!

**Comment by noah-nuebling** [comment] 2020-03-05 02:58
There's an ['official' workaround](https://mousefix.org/help/) on the website now, so I'm closing this. Thank you guys for contributing! :)

If you prevent the GateKeeper security-check after the PrefPane is installed by either removing the quarantine before installing or by disabling GateKeeper then everything works fine. But if that check runs and deems the Prefpane unsafe then the it will never open up even after approving it. There are apparently some weird bugs between Gatekeeper/Notarization and System Preferences.

**Closed as completed by noah-nuebling** 2020-03-05 02:58 UTC

**Comment by kibin** [comment] 2020-12-15 19:29
I have the same error on catalina 10.15.7, nothing from the above helped and official workaround gives me this error:
```bash
⚡︎ sudo spctl --add ~/Library/PreferencePanes/Mouse\ Fix.prefPane
/Users/al/Library/PreferencePanes/Mouse Fix.prefPane: invalid API object reference
```

**Comment by kibin** [comment] 2021-01-13 16:54
For those who gets `invalid API object reference` error, workaround, that worked for me:
Uninstall prefpane, download new one, use `sudo spctl --add <path/to/downloaded/prefpane>`, open it and proceed to install.
